### ISSUE TITLE
Clean/Organize Repository Files

### ISSUE THREAD

**Issue by bliutech** [sahil485/TouchBasedAuth#3]
Ensure that all files in the repository are needed to look professional.

**To Do:**
- [x] delete the ```.idea``` folder. It's a Pycharm specific file
- [x] remove unnecessary folders/files
- [x] make the repository public
- [x] hide the "Releases" and "Packages" tabs on the side of the repository on GitHub

**Comment by sahil485** [comment]
All feedback implemented.
